<p align="center"><img alt="udeA logo" height="150px" src="https://github.com/freddyduitama/images/blob/master/logo.png?raw=true"></p><h1><font color='0B5345'> <center>

Parcial 2: Informática II

</center></font></h1>
<h2><font color='0B5345'> <center>
Intoducción a la computación numérica en python</center></font></h2>
<font  face="Courier New" size="3">

<p3><center><b><font color='0B5345' face="Lucida Calligraphy,Comic Sans MS,Lucida Console" size="5">Universidad de Antioquia - Bioingeniería</font></b> </center></p3>


Nombre: 

Cédula:

Lea detenidamente los enunciados y desarrolle cada uno de los ejercicios, para cada uno de los ejercicios el código debe estar comentado.

1. (10%) Cree un tablero de ajedrez de tamaño 8 x 8.

    El tablero de ajedrez debe tener casillas blancas y negras alternadas, representadas por los caracteres '#' y '.' respectivamente.

2. (20%) Usando la biblioteca numpy en Python, cree una matriz cuadrada de tamaño nxn con la siguiente configuración:

- Todas las posiciones deben inicializarse en 0.
- Una cruz de unos debe formarse en el centro de la matriz.

    Cree una función llamada generar_matriz_cruz() que tome como argumento el tamaño de la matriz y devuelva la matriz resultante.

3. (10%) Cree una función llamada crear_matriz_diagonal() que genere una matriz cuadrada de tamaño nxn con valores aleatorios en la diagonal principal y ceros en el resto de las posiciones.

Para esto, sigue los siguientes pasos:

- Define el tamaño n de la matriz.
- Genera valores aleatorios que formarán la diagonal principal de la matriz.
- Inicializa una matriz de ceros del tamaño adecuado.
- Asigna los valores aleatorios a la diagonal principal de la matriz.
- Retorna la matriz resultante.

4. (60%) Análisis de Señales biomédicas:

Usando las bibliotecas scipy, matplotlib y numpy, cree una función llamada analisis_de_senal(archivo,sensor) que realice las siguientes operaciones:

- Cargue una señal desde un archivo .mat.
- Encuentre el valor máximo y su posición en la señal de uno de los sensores, con la función puede seleccionar que sensor de la señal va a utilizar.
- Gráficar en una misma figura (Las gráficas deben tener título, nombres de los ejes y color asignado). Use la forma explícita de matplotlib.
    - La señal en un intervalo donde se vea el valor maximo y con una flecha indique su ubicación y escriba el valor dentro de la gráfica.
    - Un histograma de la señal con etiquetas de medidas de tendencia central (promedio y mediana).

Muchos exitos!!

In [4]:
#Parte - 1
import numpy as np

tablero = np.full((8,8), '#', dtype=str)
for i in range(0,8):
    for j in range(0,8):
        if (i+j) % 2 == 0:
            tablero[i,j] = '.'

#print(tablero)


[['.' '#' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '#' '.']
 ['.' '#' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '#' '.']
 ['.' '#' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '#' '.']
 ['.' '#' '.' '#' '.' '#' '.' '#']
 ['#' '.' '#' '.' '#' '.' '#' '.']]


In [9]:
#Parte 2
import numpy as np

def generar_matriz_cruz(n):
    # Crear una matriz de ceros de tamaño nxn
    matriz = np.zeros((n, n), dtype=int)
    
    # Calcular el centro de la matriz
    centro = n//2



    
    # Establecer la cruz de unos en el centro
    matriz[centro, :] = 1  # Establecer fila del centro
    matriz[:, centro] = 1  # Establecer columna del centro
    
    print(matriz)

generar_matriz_cruz(5)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


In [10]:
#Parte 3

import numpy as np

def crear_matriz_diagonal(n):
    # Genera valores aleatorios para la diagonal principal
    diagonal = np.random.rand(n)
    
    # Inicializa una matriz de ceros del tamaño adecuado
    matriz = np.zeros((n, n))
    
    # Asigna los valores aleatorios a la diagonal principal de la matriz
    np.fill_diagonal(matriz, diagonal)
    
    return matriz

# Ejemplo de uso
n = 5  # Tamaño de la matriz
matriz_resultante = crear_matriz_diagonal(n)
print("Matriz generada:")
print(matriz_resultante)

Matriz generada:
[[0.50767741 0.         0.         0.         0.        ]
 [0.         0.22553103 0.         0.         0.        ]
 [0.         0.         0.58643564 0.         0.        ]
 [0.         0.         0.         0.18366489 0.        ]
 [0.         0.         0.         0.         0.97393922]]


Usando las bibliotecas scipy, matplotlib y numpy, cree una función llamada analisis_de_senal(archivo,sensor) que realice las siguientes operaciones:

- Cargue una señal desde un archivo .mat.
- Encuentre el valor máximo y su posición en la señal de uno de los sensores, con la función puede seleccionar que sensor de la señal va a utilizar.
- Gráficar en una misma figura (Las gráficas deben tener título, nombres de los ejes y color asignado). Use la forma explícita de matplotlib.
    - La señal en un intervalo donde se vea el valor maximo y con una flecha indique su ubicación y escriba el valor dentro de la gráfica.
    - Un histograma de la señal con etiquetas de medidas de tendencia central (promedio y mediana).

In [24]:
#Parte 4
import scipy.io as sio
import numpy as np
import matplotlib.pyplot as plt 

#Cargar señal

File = sio.loadmat(r'D:\Datos PC\Escritorio\Repaso Info II\Taller\senales_potencial.mat')

#print(File.keys())

infrecuente = File['infrecuente']

sensores = infrecuente.shape[0]
puntosn = infrecuente.shape[1]
epocas = infrecuente.shape[2]

infrecuente_aplanado = np.reshape(infrecuente,(sensores,puntosn*epocas),order = 'F') 
print(infrecuente_aplanado)



[[ -0.83749473  -0.9562371   -1.0724295  ...  -6.191432    -6.1184025
   -6.057742  ]
 [ -1.2637602   -1.3954667   -1.5173539  ... -10.904964   -10.851019
  -10.806169  ]
 [ -0.47651216  -0.48379016  -0.4795187  ...  -5.268532    -5.3301888
   -5.3978744 ]
 ...
 [ -1.5274851   -1.053489    -0.5758177  ...   0.0257757    0.28843728
    0.54285604]
 [ -2.6431959   -2.3996053   -2.1375208  ...   1.0747223    0.79645485
    0.52419126]
 [  2.948656     2.7546198    2.54476    ...  -0.5165161   -0.871377
   -1.1886533 ]]


In [17]:
analisis_de_senal('D:\Datos PC\Escritorio\Repaso Info II\Taller\senales_potencial.mat')